application: siftlinks
version: 1
runtime: python
api_version: 1

handlers:
- url: /assets
  static_dir: assets
  
- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon\.ico
    
- url: .*
  script: main.py

builtins:
- remote_api: on